### ISSUE TITLE
Glossary issue when 2 or more terms exist on same page

### ISSUE THREAD

**Issue by line47** [frtib/tsp-redesign#37]
@chachi69 to add more info

**Comment by chachi69** [comment]
On http://tspdev.gov.s3-website-us-east-1.amazonaws.com/manage-life-changes/entering-nonpay-status/#fers-employee-accounts only the first glossary term on the page `Agency Matching Contributions` activates the glossary. The second term, `Agency Automatic (1%) Contributions` fails to fire. This same behavior has been observed on other pages.

**Comment by line47** [comment]
@chachi69 Was the glossary built from this or just copy pasted in? 
https://github.com/18F/glossary#getting-started

**Comment by line47** [comment]
This has been fixed
